#!/bin/bash
# HTML template functions for Pact gallery

# =============================================================================
# Common Styles
# =============================================================================

readonly COMMON_STYLES='
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      min-height: 100vh;
    }
    a { color: #58a6ff; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .badge {
      display: inline-block;
      background: #21262d;
      border: 1px solid #30363d;
      border-radius: 2em;
      padding: 0.25em 0.75em;
      font-size: 0.75rem;
      margin-right: 0.5rem;
    }
'

# =============================================================================
# Main Index Page (Commit List)
# =============================================================================

# Generate main index header
render_main_header() {
  cat << 'EOF'
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pact Sample Gallery</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      min-height: 100vh;
      padding: 2rem;
    }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #58a6ff; }
    .subtitle { color: #8b949e; margin-bottom: 2rem; }
    .commit-list { list-style: none; }
    .commit-item {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 6px;
      margin-bottom: 1rem;
      transition: border-color 0.2s;
    }
    .commit-item:hover { border-color: #58a6ff; }
    .commit-link {
      display: block;
      padding: 1.5rem;
      text-decoration: none;
      color: inherit;
    }
    .commit-id {
      font-family: monospace;
      font-size: 1.25rem;
      color: #58a6ff;
      margin-bottom: 0.5rem;
    }
    .commit-meta { font-size: 0.875rem; color: #8b949e; }
    .badge {
      display: inline-block;
      background: #21262d;
      border: 1px solid #30363d;
      border-radius: 2em;
      padding: 0.25em 0.75em;
      font-size: 0.75rem;
      margin-right: 0.5rem;
    }
    footer {
      margin-top: 3rem;
      padding-top: 1.5rem;
      border-top: 1px solid #30363d;
      text-align: center;
      color: #8b949e;
      font-size: 0.875rem;
    }
    footer a { color: #58a6ff; text-decoration: none; }
    footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Pact Sample Gallery</h1>
    <p class="subtitle">Generated SVG diagrams from .pact files</p>
    <ul class="commit-list">
EOF
}

# Generate a single commit item
# Usage: render_commit_item <commit_id> <class_count> <state_count> <flow_count> <sequence_count>
render_commit_item() {
  local commit="$1"
  local class_count="$2"
  local state_count="$3"
  local flow_count="$4"
  local sequence_count="$5"

  cat << EOF
      <li class="commit-item">
        <a href="commit/$commit/" class="commit-link">
          <div class="commit-id">$commit</div>
          <div class="commit-meta">
            <span class="badge">class: $class_count</span>
            <span class="badge">state: $state_count</span>
            <span class="badge">flow: $flow_count</span>
            <span class="badge">sequence: $sequence_count</span>
          </div>
        </a>
      </li>
EOF
}

# Generate main index footer
render_main_footer() {
  cat << 'EOF'
    </ul>
    <footer>
      <p>Generated by <a href="https://github.com/tubasasakunn/pact">Pact</a></p>
    </footer>
  </div>
</body>
</html>
EOF
}

# =============================================================================
# Commit Detail Page (SVG Gallery)
# =============================================================================

# Generate commit page header
# Usage: render_commit_header <commit_id>
render_commit_header() {
  local commit="$1"

  cat << EOF
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$commit - Pact Sample Gallery</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      min-height: 100vh;
    }
    .header {
      background: #161b22;
      border-bottom: 1px solid #30363d;
      padding: 1rem 2rem;
      position: sticky;
      top: 0;
      z-index: 100;
    }
    .header-content {
      max-width: 1400px;
      margin: 0 auto;
      display: flex;
      align-items: center;
      gap: 1rem;
    }
    .back-link {
      color: #8b949e;
      text-decoration: none;
      font-size: 1.5rem;
    }
    .back-link:hover { color: #58a6ff; }
    h1 { font-size: 1.25rem; color: #c9d1d9; }
    h1 code {
      color: #58a6ff;
      background: #21262d;
      padding: 0.2em 0.5em;
      border-radius: 4px;
    }

    /* Tab Navigation */
    .tabs {
      display: flex;
      gap: 0.5rem;
      padding: 1rem 2rem;
      background: #161b22;
      border-bottom: 1px solid #30363d;
      overflow-x: auto;
    }
    .tab {
      padding: 0.5rem 1rem;
      background: transparent;
      border: 1px solid #30363d;
      border-radius: 6px;
      color: #8b949e;
      cursor: pointer;
      font-size: 0.875rem;
      white-space: nowrap;
      transition: all 0.2s;
    }
    .tab:hover {
      border-color: #58a6ff;
      color: #c9d1d9;
    }
    .tab.active {
      background: #58a6ff;
      border-color: #58a6ff;
      color: #0d1117;
    }
    .tab .count {
      background: #21262d;
      padding: 0.1em 0.5em;
      border-radius: 2em;
      margin-left: 0.5rem;
      font-size: 0.75rem;
    }
    .tab.active .count { background: rgba(0,0,0,0.2); }

    /* Content Area */
    .content { padding: 2rem; }
    .gallery {
      display: none;
      max-width: 1400px;
      margin: 0 auto;
    }
    .gallery.active { display: block; }
    .gallery-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
      gap: 1.5rem;
    }

    /* Cards */
    .card {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 8px;
      overflow: hidden;
      transition: border-color 0.2s;
    }
    .card:hover { border-color: #58a6ff; }
    .card-header {
      padding: 0.75rem 1rem;
      background: #21262d;
      border-bottom: 1px solid #30363d;
      font-size: 0.875rem;
      font-family: monospace;
      color: #8b949e;
    }
    .card-body {
      padding: 1rem;
      background: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 200px;
    }
    .card-body img {
      max-width: 100%;
      max-height: 400px;
      height: auto;
    }
    .card-footer {
      padding: 0.5rem 1rem;
      border-top: 1px solid #30363d;
      text-align: right;
    }
    .card-footer a {
      color: #58a6ff;
      text-decoration: none;
      font-size: 0.875rem;
    }
    .card-footer a:hover { text-decoration: underline; }

    /* Empty State */
    .empty-state {
      text-align: center;
      padding: 3rem;
      color: #8b949e;
    }
  </style>
</head>
<body>
  <header class="header">
    <div class="header-content">
      <a href="../../" class="back-link">&larr;</a>
      <h1>Commit <code>$commit</code></h1>
    </div>
  </header>
  <nav class="tabs">
EOF
}

# Generate tab buttons
# Usage: render_tabs <class_count> <state_count> <flow_count> <sequence_count>
render_tabs() {
  local class_count="$1"
  local state_count="$2"
  local flow_count="$3"
  local sequence_count="$4"

  cat << EOF
    <button class="tab active" data-target="class">Class <span class="count">$class_count</span></button>
    <button class="tab" data-target="state">State <span class="count">$state_count</span></button>
    <button class="tab" data-target="flow">Flow <span class="count">$flow_count</span></button>
    <button class="tab" data-target="sequence">Sequence <span class="count">$sequence_count</span></button>
  </nav>
  <main class="content">
EOF
}

# Generate gallery section start
# Usage: render_gallery_start <category> [is_active]
render_gallery_start() {
  local category="$1"
  local is_active="$2"
  local active_class=""
  [ "$is_active" = "true" ] && active_class=" active"

  cat << EOF
    <section id="$category" class="gallery$active_class">
      <div class="gallery-grid">
EOF
}

# Generate SVG card
# Usage: render_svg_card <category> <filename>
render_svg_card() {
  local category="$1"
  local filename="$2"
  local alt="${filename%.svg}"
  alt="${alt//_/ }"

  cat << EOF
        <div class="card">
          <div class="card-header">$filename</div>
          <div class="card-body"><img src="$category/$filename" alt="$alt" loading="lazy"></div>
          <div class="card-footer"><a href="$category/$filename" target="_blank">Open</a></div>
        </div>
EOF
}

# Generate gallery section end
render_gallery_end() {
  cat << 'EOF'
      </div>
    </section>
EOF
}

# Generate commit page footer with JavaScript
render_commit_footer() {
  cat << 'EOF'
  </main>
  <script>
    document.querySelectorAll('.tab').forEach(tab => {
      tab.addEventListener('click', () => {
        document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
        document.querySelectorAll('.gallery').forEach(g => g.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(tab.dataset.target).classList.add('active');
      });
    });
  </script>
</body>
</html>
EOF
}
