#!/bin/bash
# Generate GitHub Pages gallery for sample SVGs

set -e

SAMPLE_DIR="docs/sample"
COMMIT_DIR="$SAMPLE_DIR/commit"

# Generate main index.html with commit list
generate_main_index() {
  local commits=()
  for dir in "$COMMIT_DIR"/*/; do
    [ -d "$dir" ] && commits+=("$(basename "$dir")")
  done

  cat > "$SAMPLE_DIR/index.html" << 'HEADER'
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pact Sample Gallery</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      min-height: 100vh;
      padding: 2rem;
    }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #58a6ff; }
    .subtitle { color: #8b949e; margin-bottom: 2rem; }
    .commit-list { list-style: none; }
    .commit-item {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 6px;
      margin-bottom: 1rem;
      transition: border-color 0.2s;
    }
    .commit-item:hover { border-color: #58a6ff; }
    .commit-link { display: block; padding: 1.5rem; text-decoration: none; color: inherit; }
    .commit-id { font-family: monospace; font-size: 1.25rem; color: #58a6ff; margin-bottom: 0.5rem; }
    .commit-meta { font-size: 0.875rem; color: #8b949e; }
    .badge {
      display: inline-block;
      background: #21262d;
      border: 1px solid #30363d;
      border-radius: 2em;
      padding: 0.25em 0.75em;
      font-size: 0.75rem;
      margin-right: 0.5rem;
    }
    footer {
      margin-top: 3rem;
      padding-top: 1.5rem;
      border-top: 1px solid #30363d;
      text-align: center;
      color: #8b949e;
      font-size: 0.875rem;
    }
    footer a { color: #58a6ff; text-decoration: none; }
    footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Pact Sample Gallery</h1>
    <p class="subtitle">Generated SVG diagrams from .pact files</p>
    <ul class="commit-list">
HEADER

  for commit in "${commits[@]}"; do
    local class_count=$(ls -1 "$COMMIT_DIR/$commit/class/"*.svg 2>/dev/null | wc -l)
    local state_count=$(ls -1 "$COMMIT_DIR/$commit/state/"*.svg 2>/dev/null | wc -l)
    local flow_count=$(ls -1 "$COMMIT_DIR/$commit/flow/"*.svg 2>/dev/null | wc -l)
    local sequence_count=$(ls -1 "$COMMIT_DIR/$commit/sequence/"*.svg 2>/dev/null | wc -l)

    cat >> "$SAMPLE_DIR/index.html" << EOF
      <li class="commit-item">
        <a href="commit/$commit/" class="commit-link">
          <div class="commit-id">$commit</div>
          <div class="commit-meta">
            <span class="badge">class: $class_count</span>
            <span class="badge">state: $state_count</span>
            <span class="badge">flow: $flow_count</span>
            <span class="badge">sequence: $sequence_count</span>
          </div>
        </a>
      </li>
EOF
  done

  cat >> "$SAMPLE_DIR/index.html" << 'FOOTER'
    </ul>
    <footer>
      <p>Generated by <a href="https://github.com/tubasasakunn/pact">Pact</a></p>
    </footer>
  </div>
</body>
</html>
FOOTER

  echo "Generated $SAMPLE_DIR/index.html"
}

# Generate commit-specific index.html
generate_commit_index() {
  local commit="$1"
  local commit_path="$COMMIT_DIR/$commit"

  cat > "$commit_path/index.html" << HEADER
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$commit - Pact Sample Gallery</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      min-height: 100vh;
    }
    .header {
      background: #161b22;
      border-bottom: 1px solid #30363d;
      padding: 1rem 2rem;
      position: sticky;
      top: 0;
      z-index: 100;
    }
    .header-content { max-width: 1400px; margin: 0 auto; display: flex; align-items: center; gap: 1rem; }
    .back-link { color: #8b949e; text-decoration: none; font-size: 1.5rem; }
    .back-link:hover { color: #58a6ff; }
    h1 { font-size: 1.25rem; color: #c9d1d9; }
    h1 code { color: #58a6ff; background: #21262d; padding: 0.2em 0.5em; border-radius: 4px; }
    .tabs {
      display: flex;
      gap: 0.5rem;
      padding: 1rem 2rem;
      background: #161b22;
      border-bottom: 1px solid #30363d;
      overflow-x: auto;
    }
    .tab {
      padding: 0.5rem 1rem;
      background: transparent;
      border: 1px solid #30363d;
      border-radius: 6px;
      color: #8b949e;
      cursor: pointer;
      font-size: 0.875rem;
      white-space: nowrap;
      transition: all 0.2s;
    }
    .tab:hover { border-color: #58a6ff; color: #c9d1d9; }
    .tab.active { background: #58a6ff; border-color: #58a6ff; color: #0d1117; }
    .tab .count { background: #21262d; padding: 0.1em 0.5em; border-radius: 2em; margin-left: 0.5rem; font-size: 0.75rem; }
    .tab.active .count { background: rgba(0,0,0,0.2); }
    .content { padding: 2rem; }
    .gallery { display: none; max-width: 1400px; margin: 0 auto; }
    .gallery.active { display: block; }
    .gallery-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(400px, 1fr)); gap: 1.5rem; }
    .card {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 8px;
      overflow: hidden;
      transition: border-color 0.2s;
    }
    .card:hover { border-color: #58a6ff; }
    .card-header {
      padding: 0.75rem 1rem;
      background: #21262d;
      border-bottom: 1px solid #30363d;
      font-size: 0.875rem;
      font-family: monospace;
      color: #8b949e;
    }
    .card-body {
      padding: 1rem;
      background: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 200px;
    }
    .card-body img { max-width: 100%; max-height: 400px; height: auto; }
    .card-footer { padding: 0.5rem 1rem; border-top: 1px solid #30363d; text-align: right; }
    .card-footer a { color: #58a6ff; text-decoration: none; font-size: 0.875rem; }
    .card-footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <header class="header">
    <div class="header-content">
      <a href="../../" class="back-link">&larr;</a>
      <h1>Commit <code>$commit</code></h1>
    </div>
  </header>
  <nav class="tabs">
HEADER

  # Count files in each category
  local class_count=$(ls -1 "$commit_path/class/"*.svg 2>/dev/null | wc -l)
  local state_count=$(ls -1 "$commit_path/state/"*.svg 2>/dev/null | wc -l)
  local flow_count=$(ls -1 "$commit_path/flow/"*.svg 2>/dev/null | wc -l)
  local sequence_count=$(ls -1 "$commit_path/sequence/"*.svg 2>/dev/null | wc -l)

  cat >> "$commit_path/index.html" << EOF
    <button class="tab active" data-target="class">Class <span class="count">$class_count</span></button>
    <button class="tab" data-target="state">State <span class="count">$state_count</span></button>
    <button class="tab" data-target="flow">Flow <span class="count">$flow_count</span></button>
    <button class="tab" data-target="sequence">Sequence <span class="count">$sequence_count</span></button>
  </nav>
  <main class="content">
EOF

  # Generate gallery sections
  for category in class state flow sequence; do
    local is_active=""
    [ "$category" = "class" ] && is_active=" active"

    cat >> "$commit_path/index.html" << EOF
    <section id="$category" class="gallery$is_active">
      <div class="gallery-grid">
EOF

    if [ -d "$commit_path/$category" ]; then
      for svg in "$commit_path/$category/"*.svg; do
        [ -f "$svg" ] || continue
        local filename=$(basename "$svg")
        local alt=$(echo "$filename" | sed 's/\.svg$//' | sed 's/_/ /g')
        cat >> "$commit_path/index.html" << EOF
        <div class="card">
          <div class="card-header">$filename</div>
          <div class="card-body"><img src="$category/$filename" alt="$alt"></div>
          <div class="card-footer"><a href="$category/$filename" target="_blank">Open</a></div>
        </div>
EOF
      done
    fi

    cat >> "$commit_path/index.html" << 'EOF'
      </div>
    </section>
EOF
  done

  cat >> "$commit_path/index.html" << 'FOOTER'
  </main>
  <script>
    document.querySelectorAll('.tab').forEach(tab => {
      tab.addEventListener('click', () => {
        document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
        document.querySelectorAll('.gallery').forEach(g => g.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(tab.dataset.target).classList.add('active');
      });
    });
  </script>
</body>
</html>
FOOTER

  echo "Generated $commit_path/index.html"
}

# Main
echo "Generating gallery pages..."

generate_main_index

for dir in "$COMMIT_DIR"/*/; do
  [ -d "$dir" ] && generate_commit_index "$(basename "$dir")"
done

echo "Done!"
